version: 2
preset:
  image: 'gantry-admin://images/layouts/home.png'
  name: myhome
  timestamp: 1462439046
layout:
  /top/:
    -
      - position-module-2900
  /navigation/:
    -
      - menu-3057
  /header/:
    -
      - position-module-5993
  /showcase/: {  }
  /feature/: {  }
  /main/:
    -
      - position-module-7422
    -
      - position-module-4522
  /subfeature/:
    -
      - position-module-1292
  /bottom-1/:
    -
      - menu-3649
  /bottom-2/:
    -
      - position-module-4994
  /footer/:
    -
      - position-module-5179
    -
      - position-position-7084
  offcanvas:
    -
      - mobile-menu-5329
structure:
  top:
    type: section
    attributes:
      boxed: ''
  navigation:
    type: section
    attributes:
      boxed: ''
  header:
    attributes:
      boxed: ''
      class: home
  showcase:
    type: section
    attributes:
      boxed: ''
  feature:
    type: section
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
      class: home
  subfeature:
    type: section
    attributes:
      class: flush
      boxed: ''
  bottom-1:
    type: section
    attributes:
      boxed: ''
  bottom-2:
    type: section
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  position-module-2900:
    title: Logo-top
    attributes:
      module_id: '96'
      key: logo-top
    block:
      variations: center
  position-module-5993:
    title: Слайдер
    attributes:
      module_id: '87'
      key: слайдер
  position-module-7422:
    title: Статья
    attributes:
      module_id: '97'
      key: статья
  position-module-4522:
    title: 'Module Instance'
    attributes:
      module_id: '98'
      key: module-instance
  position-module-1292:
    title: Свидетельство
    attributes:
      module_id: '95'
      key: свидетельство
    block:
      variations: 'center nopaddingall'
  menu-3649:
    title: Menu-bottom
    block:
      variations: 'center nopaddingall'
  position-module-4994:
    title: Logo-bottom
    attributes:
      module_id: '94'
      key: logo-bottom
    block:
      variations: 'center nopaddingall'
  position-module-5179:
    title: Копирайт
    attributes:
      module_id: '93'
      key: копирайт
    block:
      variations: center
  position-position-7084:
    title: 'Module Position'
    attributes:
      key: footer
  mobile-menu-5329:
    title: 'Mobile Menu'
