preset: preset1
header:
  background: 'rgba(255, 255, 255, 0.00)'
  text-color: '#444444'
navigation:
  background: 'rgba(255, 255, 255, 0.00)'
  text-color: '#464646'
subfeature:
  background: 'rgba(240, 240, 240, 0.00)'
